// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsRV6Wd4lgMe0QLy1m3-uXQDu9_-iRfr8',
    appId: '1:564703876113:web:9dde2a74fd18af5c624db0',
    messagingSenderId: '564703876113',
    projectId: 'notes-8e927',
    authDomain: 'notes-8e927.firebaseapp.com',
    storageBucket: 'notes-8e927.firebasestorage.app',
    measurementId: 'G-Z39EP05VYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQgTGPRfeP7ISDqJTJsSRj6TG71w8P3y0',
    appId: '1:564703876113:android:c7233332a70b61db624db0',
    messagingSenderId: '564703876113',
    projectId: 'notes-8e927',
    storageBucket: 'notes-8e927.firebasestorage.app',
  );
}
